name: Build project
on:
  push:
    branches: [ master ]
    paths:
      - lsp-server/**
      - lsp-client/**
      - grammar-smith-app/**
      - pom.xml
      - .github/workflows/project-build.yml

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
        run: mvn -v && mvn clean compile package
